### ISSUE TITLE
Mock-up draft

### ISSUE THREAD

**Issue by Tam-Weibel** [silviesc/project-promo-v-module-1-team-1#8]
paint con el boceto de la landing page

**Comment by Avispas** [comment]
![Image](https://github.com/silviesc/project-promo-v-module-1-team-1/assets/146772859/4b50b6f0-4364-4743-82e2-622c7a9ac128)

**Comment by Tam-Weibel** [comment]
![Image](https://github.com/silviesc/project-promo-v-module-1-team-1/assets/150478824/a723c4b6-7a7d-40f9-bfc5-8e383b0bcb2c)
